# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftL' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'

  target 'SwiftLTests' do
    inherit! :search_paths
#    pod 'RxBlocking', '~> 4.0'
#    pod 'RxTest',     '~> 4.0'
  end

  target 'SwiftLUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            if config.name == 'Test'
#                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
#            end
#        end
#    end
#end
